# Generated by Django 2.2.3 on 2020-02-23 07:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_issue', '0004_auto_20200223_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 24, 7, 11, 37, 780419), verbose_name='return date'),
        ),
    ]
